version: '3.5'

services:
        redis:
           image: redis
           volumes:
             - ./data:/data
           entrypoint: redis-server --appendonly yes
           ports:
             - 6379:6379
           restart: unless-stopped

        backend:
           build: backend-example-docker/.
           container_name: backend
           environment:
                  - FRONT_URL=http://localhost:5000
                  - REDIS=redis
                  - REDIS_PORT=6379
           ports:
              - 8000:8000
           entrypoint: npm start

        frontend:
           build: frontend-example-docker/.
           container_name: frontend
           environment:
                  - API_URL=http://localhost:8000
           ports:
             - 5000:5000
           entrypoint: npm start
