# Note: Only works when you create a new folder logs with empty logs.txt file inside. I haven't found a better solution yet.

version: '3.5'
services:
        first_volume_exercise:
           image: devopsdockeruh/first_volume_exercise
           build: .
           volumes:
                   -  ./logs/logs.txt:/usr/app/logs.txt
           container_name: first_volume_exercise
