version: '3.5'

services:
        backend:
           image: backend
           build: backend/.
           environment:
                  - FRONT_URL=http://localhost:5000
           ports:
              - 8000:8000
           entrypoint: npm start

        frontend:
           image: frontend
           build: frontend/.
           environment:
                  - API_URL=http://localhost:8000
           ports:
             - 5000:5000
           entrypoint: npm start
