version: '3.5'

services:
        ml-kurkkumopo-training:
           build: ml-kurkkumopo-training/.
           container_name: training
           volumes:
              - data:/src/data
              - model:/src/model
              - imgs:/src/imgs

        ml-kurkkumopo-backend:
           build: ml-kurkkumopo-backend/.
           container_name: backend
           ports:
             - 5000:5000
           volumes:
             - model:/src/model

        ml-kurkkumopo-frontend:
           build: ml-kurkkumopo-frontend/.
           container_name: frontend
           ports:
             - 3000:3000
volumes:
    model:
    data:
    imgs:
